### ISSUE TITLE
cmake generation error

### ISSUE THREAD

**Issue by zhaofeng-shu33** [PerretB/Higra#111]
Following the instruction on README.md, I encounter the following error when running 
`cmake ../higra/`.

CMake Error at CMakeLists.txt:19 (REGISTER_PYTHON_MODULE_FILES):
  Unknown CMake command "REGISTER_PYTHON_MODULE_FILES".

I use CMake version 3.13 on CentOS 7.

**Comment by PerretB** [comment]
This is strange, pip wheels are currently built with cmake 3.13.3 so there should be no problem.

Can you check if your directory structure looks like this

- build
- Higra
|- benchmark
|- doc
|-...

and the command ``cmake ../Higra/`` is launched from the ``build`` directory.

**Comment by zhaofeng-shu33** [comment]
I found I made a `build` directory inside the `Higra` folder.
Pointing to the root `CMakeLists.txt` solves the problem.
By the way, I also find I can install the binary distribution directly using `pip` but I do not find any instructions about this way. So why not added to documentation?

**Comment by PerretB** [comment]
Installing with ``pip`` is the first thing that appears in the github readme, just after the project description :)

Do you think that I should make it more explicit that building is not required if going with ``pip install higra`` ?

**Comment by zhaofeng-shu33** [comment]
Yes, there is pip installation instruction in README. For the documentation website https://higra.readthedocs.io/en/latest/, there seems no installation instruction.
It is a common knowledge to distinguish binary and source installation. I think there is no need to specify this.
